### PR TITLE
9 actually filter

### LINKED ISSUE #9: As a user I want the filter to actually filter the events
- [x] All availiable committees can be selected or deselected
- [x] Selected committees are reflected in the event list
- [x] Good design
- [x] Works intuitively

### PR DESCRIPTION
**Pull request by MechaFlex**
Sorry it got so late. I blame being ill.

Resolves #9

### CODE REVIEW

**Comment by axoxelol1** [comment]
Fix package lock and resolve conflicts

**Review by axoxelol1 — APPROVED** [review]
lgtm

**Review by antoneekstrom — APPROVED** [review]
ser jättebra ut snygging

**Review by simonengstrm — APPROVED** [review]
lgtm

**Pull request merged**
