### PR TITLE
Fetches events from the database instead of mocked data

### PR DESCRIPTION
**Pull request by antoneekstrom**
Co-authored-by: Cabbethebaos <casper.lindh@gmail.com>
Co-authored-by: jenssandgren <jenssandgren@users.noreply.github.com>
#38

### CODE REVIEW

**Comment by axoxelol1** [comment]
@simonengstrm Build fails because it doesn't have environment variables

**Comment by simonengstrm** [comment]
> @simonengstrm Build fails because it doesn't have environment variables

Ill take a look

**Comment by simonengstrm** [comment]
@axoxelol1 https://docs.github.com/en/actions/security-guides/encrypted-secrets.
We need to add the env to the repos encrypted secrets.

**Comment by axoxelol1** [comment]
Why do:
const events = result.map((event) => JSON.parse(JSON.stringify(event)));
When you could use the type interface we have

**Comment by antoneekstrom** [comment]
> Why do: const events = result.map((event) => JSON.parse(JSON.stringify(event))); When you could use the type interface we have @antoneekstrom

@axoxelol1 
`ObjectId` from mongoDB is apparently not JSON serializable by NextJS, so we had to manually convert them first.

I should probably add the types though, and a comment, for clarity.

**Comment by axoxelol1** [comment]
Hmm, I've done exactly that in my gibbes hobby project, I'll have a look

**Comment by antoneekstrom** [comment]
Documents in mongoDB will always have an ObjectId, which is automatically generated by default. So it does feel a little unnecessary to have another id field. But the current solution does feel like a bandaid solution. I would suggest that we put the datafetching and database connection into some sort of service object that does it instead.

**Comment by simonengstrm** [comment]
As of [b5e19d5](https://github.com/axoxelol1/dat257-hasse-andersson/pull/40/commits/b5e19d54dbbda016cfe1e0c41b69078949a3c4f8) the CI is fixed.

**Comment by antoneekstrom** [comment]
@axoxelol1 Please see #42 for a potential fix.

**Review by MechaFlex — APPROVED** [review]
LeGiTiMate

**Review by axoxelol1 — APPROVED** [review]
lgtm

**Review by simonengstrm — APPROVED** [review]
Databased

**Pull request merged**
