### PR TITLE
78 see logged in events

### PR DESCRIPTION
**Pull request by MechaFlex**
Due to lack of time and energy I have not gotten this user story to a state I'm proud with.
It does its job but has some minor issues in places.

- The mobile and desktop login windows aren't kept in sync. You can log in in one of them, but other doesn't update to show that, and the windows' styles do not really match up. Something to take a closer look at once the background image story is merged in.
- I wish the dashboard page wasn't accessible at all if you aren't logged in but I didn't have time to implement that. Can probably be done with some sort of middleware or routing?
- The checks for if a user is verified does support an all powerful admin user which can see all events. However, this is implementation is very hardcoded in.
- And in general which events a user can see is only based on username, not on a customizable lookup table which I think would be preferred.

### CODE REVIEW

**Comment by simonengstrm** [comment]
I feel like you've met the acceptance critera of the user story. I feel like you've tried to implement more functionality than the user story actually stated, or you've interpreted the user story as a bigger task than it actually is. As for the dashboard accessibility depending on the logged in status - this could very much be it's own user story, so don't worry about it. Also, the design "bugs" could be put into bug issues and we can resolve them along with some others in the next sprint?

**Comment by MechaFlex** [comment]
@simonengstrm 
Yes, I agree. Most of these things weren't part of the story. And that was sort of my thinking. I noted the issues that are there so that they can be remedied hopefully in the next sprint.

**Review by simonengstrm — APPROVED** [review]
In that case I approve, let's splat some bugs next week.

**Review by axoxelol1 — APPROVED** [review]
Agree with what you have said

**Pull request merged**
