### PR TITLE
Makes the website slightly more visually pleasing

### PR DESCRIPTION
**Pull request by antoneekstrom**
Co-authored-by: jenssandgren <jenssandgren@users.noreply.github.com>
Co-authored-by: Cabbethebaos <Cabbethebaos@users.noreply.github.com>

### CODE REVIEW

**Comment by simonengstrm** [comment]
Looks a bit weird on mobile 
image
Maybe stack logo, text and filter on top of eachother etc?

**Comment by antoneekstrom** [comment]
That is true, we can change that.

**Comment by MechaFlex** [comment]
For me this is a step backwards =P

The new logo is cool, but at the same time, it does not fit in with the rest of the webpage in my opinion. The Chalmers logo in the bottom right has uneven spacing to its left and right which feels odd.
There's a random big cat image, while a cat is fine as a placeholder, it feels like it's placement hasn't been thought through.

I feel like there is some more work to be done before this PR should have been created.

**Review by MechaFlex — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by axoxelol1** [comment]
Reserving space for the scrollbar would be great, I noticed while working on search that if the search bar disappears the whole page jumps. Not sure how/if this can be done just a thought.

**Review by simonengstrm — CHANGES_REQUESTED** [review]
I would like dynamic improvements to fit mobile.

**Review by MechaFlex — CHANGES_REQUESTED** [review]
Still really not feeling this redesign, I'm sorry.

I don't even know if anything changed, I just reviewed again for some reason

**Comment by axoxelol1** [comment]
> Still really not feeling this redesign, I'm sorry.

Really no point in reviewing right now as the branch has conflicts and needs to be merged with new filter menu etc. Is anyone working on this? Otherwise feel free to look at it if you have time.

**Review by antoneekstrom — COMMENTED** [review]
wow very cool,  I approve

**Review by simonengstrm — APPROVED** [review]
I like!

**Review by axoxelol1 — APPROVED** [review]
Lgtm, event image links expire after a while so we will need to discuss that. It also currently shows old events but I don't think that is part of this US, I can fix that as soon as this is merged.

**Comment by axoxelol1** [comment]
@MechaFlex @antoneekstrom How do we say that the requested changes are addressed so we can merge?

**Review by MechaFlex — APPROVED** [review]
I still feel the design could do with a major overhaul to really have an identity, but this works for now!

**Pull request merged**
