### PR TITLE
21 Adds a timeline view

### PR DESCRIPTION
**Pull request by antoneekstrom**
Hello friends, we are adding the timeline view!!!

### CODE REVIEW

**Comment by axoxelol1** [comment]
Looks good so far

**Comment by axoxelol1** [comment]
Looks good but react is sending a message about the child components not having key prop.
https://sentry.io/answers/unique-key-prop/

**Comment by antoneekstrom** [comment]
> Looks good but react is sending a message about the child components not having key prop. https://sentry.io/answers/unique-key-prop/

oh no... this is BAD

**Review by simonengstrm — APPROVED** [review]
+1

**Review by simonengstrm — COMMENTED** [review]
+1

**Comment by antoneekstrom** [comment]
+2

**Comment by Cabbethebaos** [comment]
Can't access highlighted event link.

- [ ] Fixed

**Pull request merged**
