### PR TITLE
8 Add iCalendar

### PR DESCRIPTION
**Pull request by antoneekstrom**

### CODE REVIEW

**Review by simonengstrm — CHANGES_REQUESTED** [review]
There was some problems with the timestamps on the events when you demonstrated the functionality. Just putting this here to follow the progress.

**Comment by antoneekstrom** [comment]
@simonengstrm I fixed the dates, just forgot to add the time to them!

**Review by axoxelol1 — APPROVED** [review]
lgtm

**Review by simonengstrm — APPROVED** [review]

**Comment by antoneekstrom** [comment]
what is this build error

**Pull request merged**
