### PR TITLE
Calendar view

### PR DESCRIPTION
**Pull request by axoxelol1**
I have implemented fullcalendar (https://fullcalendar.io/) on the /calendar route. I feel like it works okay on both desktop and mobile but am open to suggestions, there are quite a few of styling options available. Obviously we need a link to get to this view from the index page but I didn't feel comfortable throwing it in here since there is an open PR about improving the UI of the index page.

Unfortunately there is a bit of a workaround with transpiling to get the fullcalendar to work for Next, so please test this on your local machine and see if it runs okay and works like it should. Don't forget to npm install.

### CODE REVIEW

**Review by simonengstrm — APPROVED** [review]
Works good on my machine (w11). I feel like the UI is a bit shaky. It looks like it tries to follow the overall "design language" of the site so far (if you can call it that), but since the UI being improved in another PR I'm comfortable with mergeing this since we'll have to improve a lot of UI components later on anyway.

**Review by MechaFlex — CHANGES_REQUESTED** [review]
I feel like the UI needs some work. Nees some margins in places. I'd also like if the whole calendar fit on my screen, at least on desktop, but mobile too if it fits. 
Resizing leaves weird scrollbar artefacts. Overall the colors aren't matching with the rest of the webpage's color scheme and text fonts.
It would be nice to have some sort of color coding by committe perhaps. And I don't care for the difference of whole-day events vs events with a specific hour time. I wish all events were of the color block format that whole day events have.
There is no way to reach the calendar from the front page. 
Some months, (eg May and August) show a completely gray row at the bottom which is unnecessary.

**Comment by axoxelol1** [comment]
>  Needs some margins in places.

Where do you want margins?

> I'd also like if the whole calendar fit on my screen, at least on desktop, but mobile too if it fits.

I'll have to do some testing with the fit then, calendar fits on my screen but I believe you have lower than 1080p so that might be it. Can you provide a screenshot as to how it looks on your device? :)

> Resizing leaves weird scrollbar artifacts.

I'll have look at this.

> It would be nice to have some sort of color coding by committee perhaps.

I feel like color coding is outside of the scope of this user story, because that would be applied to both timeline and calendar view no? But it is certainly something that we could create a user story for. I'm guessing we would want to define the colors in the database where we have the hosts.

>And I don't care for the difference of whole-day events vs events with a specific hour time. I wish all events were of the color block format that whole day events have.

Not sure I agree here honestly.

> There is no way to reach the calendar from the front page.

If you read my PR I mentioned "Obviously we need a link to get to this view from the index page but I didn't feel comfortable throwing it in here since there is an open PR about improving the UI of the index page." Do you think I should still add this? I feel like if a redesign of the index page is in the works it will only cause merge conflicts for that US.

>Some months, (eg May and August) show a completely gray row at the bottom which is unnecessary.

I'll see if there is something I can do about that.

**Comment by MechaFlex** [comment]
@axoxelol1 

I have to admit, some of my criticisms was unfair, I should have looked at the specifications of the user story more closely (and read your PR), then I would have had a better judgement of the scope of the PR.

Still, regarding margins, I want some more air, for example, "May 2022" is right up against the left wall, and the buttons in the top right are right against the screen border, as is the entire calendar.
image

The bottom rows do not fit on my smaller screen unfortunately. Well, after I resize the screen they do fit, but after resizing (by resizing I mean going in to small windowed mode, and then going back to fullscreen) the scrollbar is way to long (the main scrollbar should exist in the image below since all rows fit on the screen there). Also as you can see weird empty scrollbars just to the left of the main scrollbar. This is on Chrome.
image

> Not sure I agree here honestly.

Fair enough =)

I also wish the week began on Mondays =)

**Comment by axoxelol1** [comment]
@MechaFlex 
Totally agree about the margins, added some now and it looks way better. I unfortunately can't replicate your issues, I am both on a different operating system and browser. So I am not sure how to go about fixing those.

**Comment by MechaFlex** [comment]
@axoxelol1 
The latest push seems to fix _all_ resizing issues, so no worries there!
And the new margins really help. 

I still have some thoughts about some aesthtical design decisions, but I agree with @simonengstrm, we haven't really established a clear design language to follow just yet.

**Review by MechaFlex — APPROVED** [review]

**Comment by axoxelol1** [comment]
> The latest push seems to fix all resizing issues, so no worries there!

Great! I'm guessing it didn't like 0 margins haha.
Regarding the design decisions this is the default look of the calendar, and like you say if we establish a design language most or all of it can be overridden with custom css if I have understood correctly. There are also quite a few options available without writing css.

**Pull request merged**
