### PR TITLE
96 bug filter disappears

### PR DESCRIPTION
**Pull request by MechaFlex**
Quite a simple fix. Removed the bloat in the Page component (by removing it completely.) and solved it with a simple flexbox

### CODE REVIEW

**Comment by simonengstrm** [comment]
Wasn't the point with the page component to standardize the styling like margins etc on every page? Feels weird removing it instead of fixing the component.

**Review by simonengstrm — APPROVED** [review]
oKay thats fair

**Review by axoxelol1 — CHANGES_REQUESTED** [review]
White bar on the side of phone both on my real phone and in Firefox mobile dev. 

<details>
  <summary>Phone Screenshot</summary>
  
  
  
</details>

**Review by axoxelol1 — APPROVED** [review]
lgtm

**Pull request merged**
