### PR TITLE
48 login window

### PR DESCRIPTION
**Pull request by Cabbethebaos**
Have a look!

### CODE REVIEW

**Comment by jenssandgren** [comment]
lgtm!

**Review by simonengstrm — CHANGES_REQUESTED** [review]
Good work, I think we'll need to improve the design a little bit and fix the merge conflicts before approving, but we can do this at the meeting tomorrow. I think that would be the easiest way to go about it :)

**Review by simonengstrm — APPROVED** [review]
lgtm

**Comment by axoxelol1** [comment]
I'll have a look at the merge conflicts then merge this

**Pull request merged**
