### PR TITLE
18 gasquen

### PR DESCRIPTION
**Pull request by simonengstrm**

### CODE REVIEW

**Comment by simonengstrm** [comment]
The user story states that you should be able to filter on this even type @antoneekstrom. Although the filter hosts are still hardcoded in the sprint branch. However you can search for "gasque" and it shows all the gasques, is this OK? @MechaFlex

**Review by axoxelol1 — APPROVED** [review]
lgtm

**Comment by MechaFlex** [comment]
> The user story states that you should be able to filter on this even type @antoneekstrom. Although the filter hosts are still hardcoded in the sprint branch. However you can search for "gasque" and it shows all the gasques, is this OK? @MechaFlex 

Yes, our intention is to have a "Gasquen" host which hosts all gasquer.

**Review by MechaFlex — APPROVED** [review]
Since the host is 'Gasquen' an entry in the DB is needed to make it work with the filter.
I fixed this entry myself just now. 

So all is good!

**Pull request merged**
