### PR TITLE
1 as a developer i want to have a specified api so that i can make my contribution integrate well with the rest of the product

### PR DESCRIPTION
**Pull request by simonengstrm**
Added interfaces for Event and Host.

Have a look

### CODE REVIEW

**Comment by axoxelol1** [comment]
Hey!
A comment describing what the interface is used for would be nice.
Thanks

**Comment by simonengstrm** [comment]
@axoxelol1 Comments are now added

**Comment by axoxelol1** [comment]
Maybe id should be _id with type ObjectId? This way we can cast it easily when retrieving from database

**Comment by antoneekstrom** [comment]
Maybe link should just be a regular string instead of an URL. I just noticed that it is not JSON serializable, which makes it a little annoying to use with `getServerSideProps`. I also think it is easiest to just store a string in the database

**Comment by simonengstrm** [comment]
@antoneekstrom @axoxelol1 Changed to "_id" and type ObjectId and link to type string with latest commit.

**Review by antoneekstrom — APPROVED** [review]

**Pull request merged**
