### PR TITLE
53 login connection

### LINKED ISSUE #53: As a user I want to be able to login to the site
- [ ] Add functionality to process a login request to the backend

### PR DESCRIPTION
**Pull request by MechaFlex**
I got the login and authorization working.

Some things I am unsure about are code structure/placement and error handling, and is something I would like to discuss more next week I feel.

Resolves #53

### CODE REVIEW

**Review by simonengstrm — CHANGES_REQUESTED** [review]
9k deletions from package lock seems like a mistake? Also is sprint not merged with your branch? A lot of conflicts. Also the build tests doesn't pass.

**Review by antoneekstrom — COMMENTED** [review]
I like the little details such as the "Unhandled Runtime Error" after you login, good stuff!

**Review by axoxelol1 — CHANGES_REQUESTED** [review]
After logging in I also receive an error

>Unhandled Runtime Error
>SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

I feel like we should roll this user story over for next week as well because the UX with popups and such feels very rough.

**Comment by MechaFlex** [comment]
@antoneekstrom @axoxelol1 

These runtime errors do not show up for me =(

> so you should probably include something about that in the readme

There is information about the JWT secret in the readme =)

> Also don't really like to have a file named jwtest, is this just a test or permanent?

It's not intended to be permanent. I wanted a reference so everyone can see how verification can be implemented. This file can be removed once verification is implemented in the dashboard for example.

> I feel like we should roll this user story over for next week as well because the UX with popups and such feels very rough.

I agree. 

> Also, your package-lock seems weird.

I reinstalled packagelock and that seemed to have helped, but now CI fails 🙃

**Comment by MechaFlex** [comment]
I realized I had placed basically all the code in the frontend, when a lot of it should have been in the backend.
I feel like I really have learned a lot about APIs and passwords and hashing and security and tokens and authorization and authentication.
I feel like finally everything is in the right place and working as intended. This 5p user story took me a lot longer than expected, and I think I've made most of the mistakes I could have made along the way.
I'm writing this at 3 in the morning.

**Comment by axoxelol1** [comment]
Nothing happens when i press login, also getting this in console:
image

Is there any way for me to test if this is working? I'm not getting any response in UI or console :/

Also, do we need the same JWT secrets? Since I'm guessing it hashes in the database differently otherwise and accounts will not work with the same password on different computers, just a guess though.

**Comment by MechaFlex** [comment]
> Is there any way for me to test if this is working? I'm not getting any response in UI or console :/

Hmm weird. It worked just fine on my machine =(
You can check the network tab in the console to see each api call and their responses. I have added some error messages so hopefully that might give a clue on what is wrong....

> Also, do we need the same JWT secrets? Since I'm guessing it hashes in the database differently otherwise and accounts will not work with the same password on different computers, just a guess though.

JWT secret has nothing to do with the hashing. The hashing algorithms are always the same.
The JWT secret is for creating tokens which is done individiually on each server instance, so this isn't the issue.

**Comment by axoxelol1** [comment]
Seems to be working ye, but please have a look at https://github.com/vercel/next.js/issues/10439#issuecomment-583214126, so we can avoid the stalled requests.

**Review by simonengstrm — APPROVED** [review]
Works on my machine and i agree with @axoxelol1 regarding the stalled requests. I also guess that the visual feedback is part of another user story. So I'll leave that out.

**Pull request merged**
