### PR TITLE
63 image background

### PR DESCRIPTION
**Pull request by Cabbethebaos**
Have a look!

### CODE REVIEW

**Comment by axoxelol1** [comment]
Ser väldigt snyggt ut, tycker dock det är lite svårt att läsa den svarta texten på vissa av bilderna. Har ni några idéer på hur vi kan lösa det?

**Review by axoxelol1 — APPROVED** [review]
lgtm

**Review by simonengstrm — CHANGES_REQUESTED** [review]
I feel like the opacity needs to be even lowered to about 50. It makes the text actually pop from the background a little bit so that it's easier to read. Also I think the slideshow needs to be slower, right now it takes too much focus from the content and I find it distracting when it changes all the time. Maybe change once every minute or two?

**Comment by MechaFlex** [comment]
I personally agree with Simon, I think the time between transitions should be increased as well as the transition speed should be decreased. Currently I think it's a bit too distracting =)

**Comment by antoneekstrom** [comment]
I haven't looked at it

**Review by simonengstrm — APPROVED** [review]

**Pull request merged**
