### PR TITLE
52 edit events

### PR DESCRIPTION
**Pull request by simonengstrm**
Adds functionality to edit events on the dashboard. localhost:3000/dashboard

### CODE REVIEW

**Review by MechaFlex — APPROVED** [review]
Other than it being being difficult to see that the text fields in the edit menu since they lack any border or color difference from the background this works really well!

**Comment by simonengstrm** [comment]
> Other than it being being difficult to see that the text fields in the edit menu since they lack any border or color difference from the background this works really well!
> 
> The log shows the following warning: `API resolved without sending a response for /api/events/getall, this may result in stalled requests.` I can't see why though, since getAll sends responses back...

I noticed the problem with getAll aswell, initially I thought it was because i use json instead of send to reply to the response, but it doesn't seem to matter weirdly. Do you want it resolved or is it ok if we leave it in. Doesn't really affect anything.

**Comment by simonengstrm** [comment]
I can also change the lightbox color a little bit and darken the background of the modal dialog like this if that is better?
Screenshot 2022-05-08 at 13 58 29

**Comment by MechaFlex** [comment]
@simonengstrm 

> Do you want it resolved or is it ok if we leave it in. Doesn't really affect anything.

I approved the review because I thought it was fine leaving is as it is. 
Darkening the background of the modal dialog would be a good change imo!

**Review by axoxelol1 — APPROVED** [review]
lgtm

**Review by antoneekstrom — APPROVED** [review]
Looks good! Some input fields in the UI could use some work though

**Pull request merged**
